use datawarehouse

-- Retrieve a list of unique countries from which customers originate

select distinct country from gold.dim_customers


-- Determine the first and last order date and the total duration in months

select min(order_date) as first_orderdate,max(order_date) as last_orderdate,DATEDIFF(month,min(order_date),max(order_date)) as duration_in_months from gold.fact_sales

--find youngest and eldest customers dirthdate and there ages---

select min(birthdate) as oldest_bdate,
datediff(year,min(birthdate),getdate()) as eldest_cust_age,
max(birthdate) as youngest_bdate,
datediff(year,max(birthdate),getdate()) as youngest_cust_age
from gold.dim_customers


--find total sales ---

select sum(sales_amount) as total_sales from gold.fact_sales

-- Find how many items are sold

select sum(quantity) as total_quantity from gold.fact_sales

-- Find the average selling price

select avg(price) as avg_price from gold.fact_sales

-- Find the Total number of Orders

select COUNT(order_number) as total_orders from gold.fact_sales
select COUNT(distinct order_number) as total_orders from gold.fact_sales

-- Find the total number of products

select COUNT(product_name) as total_products from gold.dim_products

-- Find the total number of Customers

select COUNT(customer_key) as total_customers from gold.dim_customers

-- Find the total number of customers that has placed an order

select COUNT(distinct customer_key) as total_customers from gold.dim_customers


-- Generate a Report that shows all key metrics of the business

select 'Total Sales' as Measure_name ,sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity',sum(quantity) from gold.fact_sales
union all
select 'Average Price',Avg(price) from gold.fact_sales
union all
select 'Total Orders',count(order_number) from gold.fact_sales
union all
select 'Total Products',count(distinct product_key) from gold.fact_sales
union all
select 'Total Customers',count(customer_key) from gold.fact_sales

select * from gold.fact_sales


-- Find total customers by countries

select country,COUNT(customer_key) as total_customers from gold.dim_customers group by country
order by total_customers desc

-- Find total customers by gender

select gender,COUNT(*) as total_customers from gold.dim_customers group by gender order by total_customers  desc

-- Find total products by category

select category ,count(product_key) as total_products from gold.dim_products group by category order by total_products desc

-- What is the average costs in each category?

select category ,avg(cost) as avg_cost from gold.dim_products group by category order by avg_cost desc

-- What is the total revenue generated for each category?

select p.category ,
sum(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key 
group by p.category order by total_revenue desc



-- What is the total revenue generated by each customer?

select c.first_name ,
c.last_name , sum(f.sales_amount) as total_revenue
from gold.fact_sales f left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.first_name,
c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?

select c.country,
sum(f.quantity) as total_quantity
from gold.fact_sales f left join  gold.dim_customers c
on c.customer_key = f.customer_key 
group by c.country order by total_quantity

-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking

select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f left join gold.dim_products p 
on p.product_key = f.product_key
group by p.product_name
order by total_revenue desc

-- Which 5 products Generating the LOWEST Revenue?
-- Simple Ranking

select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f left join gold.dim_products p 
on p.product_key = f.product_key
group by p.product_name
order by total_revenue 

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
